<?php

namespace TeleinfoHandler;

include_once 'TeleinfoHandlerEventsInterface.php';
include_once 'TeleinfoPacket.php';

/**
 * Teleinfo handler observer interface
 * 
 * All observers added to TeleinfoHandler must implement this interface.
 * 
 * @author     Gaël Le Moëllic <gael.lm@gmail.com>
 * @version    Release: 1.0
 * @since      Class available since Release 1.0
 */
interface TeleinfoHandlerObserverInterface extends TeleinfoHandlerEventsInterface {

    /**
     * This method permit to set the teleinfo packet.
     * 
     * @param TeleinfoPacket $teleinfoPacket packet received by the teleinfo handler
     */
    public function setTeleinfoPacket(TeleinfoPacket $teleinfoPacket);
    
    /**
     * This method permit to set the teleinfo event cause.
     * 
     * @param string $event event string generated by the teleinfo handler
     */
    public function setTeleinfoEvent($event);
    
    /**
     * This method will be called on each teleinfo events and executed on a different
     * thread.
     */
    public function notify();

}
